package gabriel.hb.MyLifeBackend.services;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.client.RestTemplate;

import gabriel.hb.MyLifeBackend.entities.LotofacilBet;
import gabriel.hb.MyLifeBackend.entities.LotofacilBetNumber;
import gabriel.hb.MyLifeBackend.entities.LotofacilDraw;
import gabriel.hb.MyLifeBackend.entities.LotofacilDrawNumber;
import gabriel.hb.MyLifeBackend.repositories.LotofacilBetRepository;
import gabriel.hb.MyLifeBackend.repositories.LotofacilDrawRepository;
import gabriel.hb.MyLifeBackend.resources.dto.PlaceBetRequest;
import gabriel.hb.MyLifeBackend.services.dto.CaixaDraw;
import gabriel.hb.MyLifeBackend.services.exceptions.DatabaseException;
import gabriel.hb.MyLifeBackend.services.exceptions.ResourceNotFoundException;

@Service /* Registra a classe como um componente/service do spring e vai poder ser injetado no LotofacilBetResource */
public class LotofacilBetService {
	
	/* O Spring resolve essa injeção de dependencia e associar uma instancia de LotofacilBetRepository */
	@Autowired private LotofacilBetRepository repository;
	@Autowired private LotofacilDrawRepository drawRepository;
	
	private final String CAIXA_API_URL = "https://servicebus2.caixa.gov.br/portaldeloterias/api/lotofacil/";
	
    /* Listar de todos os concursos */
	public List<LotofacilBet> findAll(){
		return repository.findAll();
	}
	
    /* Consultar concurso por Id */
	public LotofacilBet findById(Long id) {
        Optional<LotofacilBet> obj = repository.findById(id); // o findById retona um Optional
        return obj.orElseThrow(() -> new ResourceNotFoundException(id));
	}
	
	public List<LotofacilBet> findByTargetDrawId(Long targetDrawId) {
		List<LotofacilBet> list = repository.findByTargetDrawId(targetDrawId);
	    if (list.isEmpty()) throw new ResourceNotFoundException(targetDrawId);
	    return list;
	}
	
	/* Inserir nova aposta - Refatorado para usar a avaliação unificada */
	@Transactional
	public LotofacilBet insert(PlaceBetRequest dto) {
		LotofacilBet bet = new LotofacilBet();
        bet.setBetDate(dto.getBetDate());
        bet.setTargetDrawId(dto.getTargetDrawId());
        bet.setCost(3.50);
        bet.setAutoGenerated(dto.isAutoGenerated());
        bet.setChecked(false);
        bet.setHits(0);

        for (Integer num : dto.getBetNumbers()) {
            LotofacilBetNumber betNumber = new LotofacilBetNumber();
            betNumber.setNumber(num);
            betNumber.setBet(bet); 
            bet.getBetNumbers().add(betNumber);
        }

        // Obtém dezenas do concurso anterior (se existir)
        List<Integer> previousNumbers = getPreviousDrawNumbers(dto.getTargetDrawId());
        
        // Tenta obter o concurso alvo (se já existir no banco)
        Optional<LotofacilDraw> targetDrawOpt = drawRepository.findById(dto.getTargetDrawId());
        LotofacilDraw targetDraw = targetDrawOpt.orElse(null);
        List<Integer> targetNums = null;
        List<CaixaDraw.RateioPremio> premios = null;

        if (targetDraw != null) {
            targetNums = targetDraw.getDrawNumbers().stream()
                    .map(LotofacilDrawNumber::getNumber).collect(Collectors.toList());
            
            // Se for oficial, busca os prêmios na hora para aposta antiga
            if (targetDraw.isOfficial()) {
                try {
                    RestTemplate rt = new RestTemplate();
                    CaixaDraw apiDraw = rt.getForObject(CAIXA_API_URL + dto.getTargetDrawId(), CaixaDraw.class);
                    if (apiDraw != null) premios = apiDraw.getListaRateioPremio();
                } catch(Exception ignored) {}
            }
        }

        // Passa por avaliação de acertos, paridade e repetições
        evaluateBet(bet, targetNums, previousNumbers, targetDraw, premios);

		return repository.save(bet);
	}
	
	/* Método ÚNICO que resolve as apostas do concurso salvo e as repetições do concurso seguinte */
	@Transactional
	public void processBetsForDraw(LotofacilDraw savedDraw, CaixaDraw caixaDraw) {
	    List<CaixaDraw.RateioPremio> premios = (caixaDraw != null) ? caixaDraw.getListaRateioPremio() : null;

	    // 1. Processar apostas do concurso atual (Acertos, Paridade, Prêmios e Repetição baseada no concurso N-1)
	    List<LotofacilBet> currentBets = repository.findByTargetDrawId(savedDraw.getId());
	    if (!currentBets.isEmpty()) {
	        List<Integer> currentDrawNumbers = savedDraw.getDrawNumbers().stream()
	                .map(LotofacilDrawNumber::getNumber).collect(Collectors.toList());
	        
	        List<Integer> previousNumbers = getPreviousDrawNumbers(savedDraw.getId());

	        for (LotofacilBet bet : currentBets) {
	            evaluateBet(bet, currentDrawNumbers, previousNumbers, savedDraw, premios);
	        }
	        repository.saveAll(currentBets);
	    }

	    // 2. Processar apostas do PRÓXIMO concurso (apenas atualizar a Repetição baseada no concurso recém salvo)
	    List<LotofacilBet> futureBets = repository.findByTargetDrawId(savedDraw.getId() + 1);
	    if (!futureBets.isEmpty()) {
	        List<Integer> officialNumbersForFuture = savedDraw.getDrawNumbers().stream()
	                .map(LotofacilDrawNumber::getNumber).collect(Collectors.toList());
	        
	        for (LotofacilBet bet : futureBets) {
	            evaluateBet(bet, null, officialNumbersForFuture, null, null);
	        }
	        repository.saveAll(futureBets);
	    }
	}

    // Retorna a lista de dezenas do concurso anterior
	private List<Integer> getPreviousDrawNumbers(Long currentDrawId) {
	    List<Integer> previousNumbers = new ArrayList<>();
	    Optional<LotofacilDraw> previousDrawOpt = drawRepository.findById(currentDrawId - 1);
	    if (previousDrawOpt.isPresent()) {
	        previousNumbers = previousDrawOpt.get().getDrawNumbers().stream()
	                .map(LotofacilDrawNumber::getNumber).collect(Collectors.toList());
	    }
	    return previousNumbers;
	}

	/* Motor de Regras: Centraliza os cálculos dinamicamente se as informações existirem */
	private void evaluateBet(LotofacilBet bet, List<Integer> targetDrawNumbers, List<Integer> previousNumbers, LotofacilDraw targetDraw, List<CaixaDraw.RateioPremio> premios) {
	    int hits = 0;
	    int repeatedCount = 0;
	    int evenCount = 0;
	    int oddCount = 0;

	    for (LotofacilBetNumber betNumber : bet.getBetNumbers()) {
	        int num = betNumber.getNumber();
	        
	        // Paridade
	        if (num % 2 == 0) evenCount++;
	        else oddCount++;
	        
	        // Repetições (só avalia se a lista do anterior for preenchida)
	        if (previousNumbers != null && !previousNumbers.isEmpty()) {
	            boolean isRep = previousNumbers.contains(num);
	            betNumber.setIsRepeated(isRep);
	            if (isRep) repeatedCount++;
	        }
	        
	        // Acertos (só avalia se o concurso alvo já tiver ocorrido)
	        if (targetDrawNumbers != null) {
	            if (targetDrawNumbers.contains(num)) {
	                betNumber.setWasCorrectly(true);
	                hits++;
	            } else {
	                betNumber.setWasCorrectly(false);
	            }
	        }
	    }

	    bet.setEvenCount(evenCount);
	    bet.setOddCount(oddCount);
	    if (previousNumbers != null && !previousNumbers.isEmpty()) {
	        bet.setRepeatedCount(repeatedCount);
	    }

	    // Consolida resultados finais de conferência e prêmios
	    if (targetDraw != null) {
	        bet.setHits(hits);
	        bet.setChecked(true);
	        bet.setRealDraw(targetDraw);

	        double prizeValue = 0.0;
	        if (hits >= 11 && premios != null && targetDraw.isOfficial()) {
	            String targetDesc = hits + " acertos";
	            for (CaixaDraw.RateioPremio r : premios) {
	                if (r.getDescricaoFaixa().toLowerCase().contains(targetDesc)) {
	                    prizeValue = r.getValorPremio();
	                    break;
	                }
	            }
	        }
	        bet.setPrize(prizeValue);
	    }
	}
	
	public void delete(Long id) {
	    try {
	        if (repository.existsById(id)) repository.deleteById(id);			
	        else throw new ResourceNotFoundException(id);		
	    } catch (DataIntegrityViolationException e) {			
	        throw new DatabaseException(e.getMessage());		
	    }	
	}
}