package gabriel.hb.MyLifeBackend.services;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.VerticalAlignment;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.ss.util.RegionUtil;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.client.RestTemplate;

import gabriel.hb.MyLifeBackend.entities.LotofacilBet;
import gabriel.hb.MyLifeBackend.entities.LotofacilBetNumber;
import gabriel.hb.MyLifeBackend.entities.LotofacilDraw;
import gabriel.hb.MyLifeBackend.entities.LotofacilDrawNumber;
import gabriel.hb.MyLifeBackend.repositories.LotofacilBetRepository;
import gabriel.hb.MyLifeBackend.repositories.LotofacilDrawRepository;
import gabriel.hb.MyLifeBackend.repositories.projection.BetSummaryProjection;
import gabriel.hb.MyLifeBackend.repositories.projection.ParityGroupProjection;
import gabriel.hb.MyLifeBackend.repositories.projection.RepetitionGroupProjection;
import gabriel.hb.MyLifeBackend.resources.dto.BetGraphicsResponse;
import gabriel.hb.MyLifeBackend.resources.dto.BetSummaryResponse;
import gabriel.hb.MyLifeBackend.resources.dto.PlaceBetRequest;
import gabriel.hb.MyLifeBackend.services.dto.CaixaDraw;
import gabriel.hb.MyLifeBackend.services.exceptions.DatabaseException;
import gabriel.hb.MyLifeBackend.services.exceptions.ResourceNotFoundException;

@Service /* Registra a classe como um componente/service do spring e vai poder ser injetado no LotofacilBetResource */
public class LotofacilBetService {
	
	/* O Spring resolve essa injeção de dependencia e associar uma instancia de LotofacilBetRepository */
	@Autowired private LotofacilBetRepository repository;
	@Autowired private LotofacilDrawRepository drawRepository;
	
	private final String CAIXA_API_URL = "https://servicebus2.caixa.gov.br/portaldeloterias/api/lotofacil/";
	
    /* Listar de todos os concursos */
	public List<LotofacilBet> findAll(){
		return repository.findAll();
	}
	
    /* Consultar concurso por Id */
	public LotofacilBet findById(Long id) {
        Optional<LotofacilBet> obj = repository.findById(id); // o findById retona um Optional
        return obj.orElseThrow(() -> new ResourceNotFoundException(id));
	}
	
	public List<LotofacilBet> findByTargetDrawId(Long targetDrawId) {
		List<LotofacilBet> list = repository.findByTargetDrawId(targetDrawId);
	    if (list.isEmpty()) throw new ResourceNotFoundException(targetDrawId);
	    return list;
	}
	
	/* Inserir nova aposta - Refatorado para usar a avaliação unificada */
	@Transactional
	public LotofacilBet insert(PlaceBetRequest dto) {
		LotofacilBet bet = new LotofacilBet();
        bet.setBetDate(dto.getBetDate());
        bet.setTargetDrawId(dto.getTargetDrawId());
        bet.setCost(3.50);
        bet.setAutoGenerated(dto.isAutoGenerated());
        bet.setChecked(false);
        bet.setHits(0);

        for (Integer num : dto.getBetNumbers()) {
            LotofacilBetNumber betNumber = new LotofacilBetNumber();
            betNumber.setNumber(num);
            betNumber.setBet(bet); 
            bet.getBetNumbers().add(betNumber);
        }

        // Obtém dezenas do concurso anterior (se existir)
        List<Integer> previousNumbers = getPreviousDrawNumbers(dto.getTargetDrawId());
        
        // Tenta obter o concurso alvo (se já existir no banco)
        Optional<LotofacilDraw> targetDrawOpt = drawRepository.findById(dto.getTargetDrawId());
        LotofacilDraw targetDraw = targetDrawOpt.orElse(null);
        List<Integer> targetNums = null;
        List<CaixaDraw.RateioPremio> premios = null;

        if (targetDraw != null) {
            targetNums = targetDraw.getDrawNumbers().stream()
                    .map(LotofacilDrawNumber::getNumber).collect(Collectors.toList());
            
            // Se for oficial, busca os prêmios na hora para aposta antiga
            if (targetDraw.isOfficial()) {
                try {
                    RestTemplate rt = new RestTemplate();
                    CaixaDraw apiDraw = rt.getForObject(CAIXA_API_URL + dto.getTargetDrawId(), CaixaDraw.class);
                    if (apiDraw != null) premios = apiDraw.getListaRateioPremio();
                } catch(Exception ignored) {}
            }
        }

        // Passa por avaliação de acertos, paridade e repetições
        evaluateBet(bet, targetNums, previousNumbers, targetDraw, premios);

		return repository.save(bet);
	}
	
	/* Método ÚNICO que resolve as apostas do concurso salvo e as repetições do concurso seguinte */
	@Transactional
	public void processBetsForDraw(LotofacilDraw savedDraw, CaixaDraw caixaDraw) {
	    List<CaixaDraw.RateioPremio> premios = (caixaDraw != null) ? caixaDraw.getListaRateioPremio() : null;

	    // 1. Processar apostas do concurso atual (Acertos, Paridade, Prêmios e Repetição baseada no concurso N-1)
	    List<LotofacilBet> currentBets = repository.findByTargetDrawId(savedDraw.getId());
	    if (!currentBets.isEmpty()) {
	        List<Integer> currentDrawNumbers = savedDraw.getDrawNumbers().stream()
	                .map(LotofacilDrawNumber::getNumber).collect(Collectors.toList());
	        
	        List<Integer> previousNumbers = getPreviousDrawNumbers(savedDraw.getId());

	        for (LotofacilBet bet : currentBets) {
	            evaluateBet(bet, currentDrawNumbers, previousNumbers, savedDraw, premios);
	        }
	        repository.saveAll(currentBets);
	    }

	    // 2. Processar apostas do PRÓXIMO concurso (apenas atualizar a Repetição baseada no concurso recém salvo)
	    List<LotofacilBet> futureBets = repository.findByTargetDrawId(savedDraw.getId() + 1);
	    if (!futureBets.isEmpty()) {
	        List<Integer> officialNumbersForFuture = savedDraw.getDrawNumbers().stream()
	                .map(LotofacilDrawNumber::getNumber).collect(Collectors.toList());
	        
	        for (LotofacilBet bet : futureBets) {
	            evaluateBet(bet, null, officialNumbersForFuture, null, null);
	        }
	        repository.saveAll(futureBets);
	    }
	}

    // Retorna a lista de dezenas do concurso anterior
	private List<Integer> getPreviousDrawNumbers(Long currentDrawId) {
	    List<Integer> previousNumbers = new ArrayList<>();
	    Optional<LotofacilDraw> previousDrawOpt = drawRepository.findById(currentDrawId - 1);
	    if (previousDrawOpt.isPresent()) {
	        previousNumbers = previousDrawOpt.get().getDrawNumbers().stream()
	                .map(LotofacilDrawNumber::getNumber).collect(Collectors.toList());
	    }
	    return previousNumbers;
	}

	/* Motor de Regras: Centraliza os cálculos dinamicamente se as informações existirem */
	private void evaluateBet(LotofacilBet bet, List<Integer> targetDrawNumbers, List<Integer> previousNumbers, LotofacilDraw targetDraw, List<CaixaDraw.RateioPremio> premios) {
	    int hits = 0;
	    int repeatedCount = 0;
	    int evenCount = 0;
	    int oddCount = 0;

	    for (LotofacilBetNumber betNumber : bet.getBetNumbers()) {
	        int num = betNumber.getNumber();
	        
	        // Paridade
	        if (num % 2 == 0) evenCount++;
	        else oddCount++;
	        
	        // Repetições (só avalia se a lista do anterior for preenchida)
	        if (previousNumbers != null && !previousNumbers.isEmpty()) {
	            boolean isRep = previousNumbers.contains(num);
	            betNumber.setIsRepeated(isRep);
	            if (isRep) repeatedCount++;
	        }
	        
	        // Acertos (só avalia se o concurso alvo já tiver ocorrido)
	        if (targetDrawNumbers != null) {
	            if (targetDrawNumbers.contains(num)) {
	                betNumber.setWasCorrectly(true);
	                hits++;
	            } else {
	                betNumber.setWasCorrectly(false);
	            }
	        }
	    }

	    bet.setEvenCount(evenCount);
	    bet.setOddCount(oddCount);
	    if (previousNumbers != null && !previousNumbers.isEmpty()) {
	        bet.setRepeatedCount(repeatedCount);
	    }

	    // Consolida resultados finais de conferência e prêmios
	    if (targetDraw != null) {
	        bet.setHits(hits);
	        bet.setChecked(true);
	        bet.setRealDraw(targetDraw);

	        double prizeValue = 0.0;
	        if (hits >= 11 && premios != null && targetDraw.isOfficial()) {
	            String targetDesc = hits + " acertos";
	            for (CaixaDraw.RateioPremio r : premios) {
	                if (r.getDescricaoFaixa().toLowerCase().contains(targetDesc)) {
	                    prizeValue = r.getValorPremio();
	                    break;
	                }
	            }
	        }
	        bet.setPrize(prizeValue);
	    }
	}
	
	public void delete(Long id) {
	    try {
	        if (repository.existsById(id)) repository.deleteById(id);			
	        else throw new ResourceNotFoundException(id);		
	    } catch (DataIntegrityViolationException e) {			
	        throw new DatabaseException(e.getMessage());		
	    }	
	}
	
	public BetSummaryResponse getSummary() {
	    BetSummaryProjection projection = repository.getBetSummaryData();
	    
	    // O Saldo deve considerar o custo de TODAS, mas o prêmio de TODAS (que é 0 para as não conferidas)
	    Double balance = projection.getTotalReturn() - projection.getTotalInvested();
	    
	    Double averageHits = repository.getAverageHits(); // Agora filtrado por isChecked = true
	    Long totalWinningBets = repository.countWinningBetsChecked(); // Agora filtrado
	    Long totalChecked = repository.countAllCheckedBets();
	    
	    // Cálculo de taxa de vitória (Ex: 0.15 para 15%)
	    Double winRate = (totalChecked > 0) ? (totalWinningBets.doubleValue() / totalChecked) : 0.0;

	    return new BetSummaryResponse(
	        projection.getTotalBets(),
	        projection.getTotalInvested(),
	        projection.getTotalReturn(),
	        balance,
	        averageHits,
	        repository.countByAutoGeneratedTrue(),
	        repository.countByAutoGeneratedFalse(),
	        totalWinningBets,
	        winRate // Adicione este campo ao seu DTO no Java e no Angular
	    );
	}

	// Novo método para retornar os dados dos gráficos
	public BetGraphicsResponse getGraphicsData() {
	    List<ParityGroupProjection> parities = repository.getBetsGroupedByParity();
	    List<RepetitionGroupProjection> repetitions = repository.getBetsGroupedByRepetition();
	    Long parityHits = repository.countExactParityHits();
	    Long repetitionHits = repository.countExactRepetitionHits();

	    return new BetGraphicsResponse(parities, repetitions, parityHits, repetitionHits);
	}

	public Page<LotofacilBet> findAllPaginated(Pageable pageable) {
	    return repository.findAll(pageable);
	}

	public byte[] exportBetsToExcel() {
	    List<LotofacilBet> bets = repository.findAll();
	    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");

	    try (Workbook workbook = new XSSFWorkbook(); ByteArrayOutputStream out = new ByteArrayOutputStream()) {
	        Sheet sheet = workbook.createSheet("Relatório de Apostas");

	        // --- ESTILOS ---
	        CellStyle headerStyle = createStyle(workbook, IndexedColors.GREY_25_PERCENT, true);
	        CellStyle borderStyle = createStyle(workbook, null, false);
	        CellStyle repeatedStyle = createStyle(workbook, IndexedColors.LEMON_CHIFFON, false);
	        CellStyle hitStyle = createStyle(workbook, IndexedColors.LIGHT_GREEN, false);
	        
	        CellStyle mergedStyle = createStyle(workbook, null, false);
	        mergedStyle.setVerticalAlignment(VerticalAlignment.CENTER);

	        int rowIdx = 2;

	        for (LotofacilBet bet : bets) {
	            int startRow = rowIdx; 
	            int apostadosRowIdx = rowIdx + 1;
	            int sorteadosRowIdx = rowIdx + 2;

	            // 1. CABEÇALHO DO BLOCO
	            Row headerRow = sheet.createRow(rowIdx++);
	            String[] cols = {"", "Data Aposta", "Concurso", "", "Dezenas", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Qtd Impar", "Qtd Par", "Qtd Rep", "Qtd Acert", "Prêmio"};
	            
	            // Alteração 1: Começamos a pintar do índice 1 até o 23 (ignorando o 0 que é a margem)
	            for (int i = 1; i < cols.length; i++) {
	                Cell cell = headerRow.createCell(i);
	                cell.setCellValue(cols[i]);
	                cell.setCellStyle(headerStyle); // Agora TODAS as células do cabeçalho recebem a cor
	            }
	            sheet.addMergedRegion(new CellRangeAddress(startRow, startRow, 4, 18));

	            // 2. LINHA: APOSTADOS
	            Row rowApostados = sheet.createRow(rowIdx++);
	            List<LotofacilBetNumber> betNumbers = new ArrayList<>(bet.getBetNumbers());
	            betNumbers.sort(Comparator.comparingInt(LotofacilBetNumber::getNumber));

	            fillCell(rowApostados, 1, bet.getBetDate() != null ? bet.getBetDate().format(dtf) : "", mergedStyle);
	            fillCell(rowApostados, 2, bet.getTargetDrawId().toString(), mergedStyle);
	            fillCell(rowApostados, 22, String.valueOf(bet.getHits()), mergedStyle);
	            fillCell(rowApostados, 23, bet.getPrize() != null ? String.format("%.2f", bet.getPrize()) : "0.00", mergedStyle);

	            fillCell(rowApostados, 3, "Apostados", createStyle(workbook, null, true));

	            int colIdx = 4;
	            for (LotofacilBetNumber bn : betNumbers) {
	                Cell cell = rowApostados.createCell(colIdx++);
	                cell.setCellValue(bn.getNumber());
	                cell.setCellStyle(bn.getIsRepeated() ? repeatedStyle : borderStyle);
	            }
	            
	            fillNumericCell(rowApostados, 19, bet.getOddCount(), borderStyle);
	            fillNumericCell(rowApostados, 20, bet.getEvenCount(), borderStyle);
	            fillNumericCell(rowApostados, 21, bet.getRepeatedCount(), borderStyle);

	            // 3. LINHA: SORTEADOS
	            Row rowSorteados = sheet.createRow(rowIdx++);
	            rowSorteados.createCell(1).setCellStyle(mergedStyle);
	            rowSorteados.createCell(2).setCellStyle(mergedStyle);
	            rowSorteados.createCell(22).setCellStyle(mergedStyle);
	            rowSorteados.createCell(23).setCellStyle(mergedStyle);

	            fillCell(rowSorteados, 3, "Sorteados", createStyle(workbook, null, true));

	            if (bet.isChecked() && bet.getRealDraw() != null) {
	                Set<Integer> hitSet = betNumbers.stream().filter(LotofacilBetNumber::isWasCorrectly).map(LotofacilBetNumber::getNumber).collect(Collectors.toSet());
	                List<Integer> drawnNumbers = bet.getRealDraw().getDrawNumbers().stream().map(LotofacilDrawNumber::getNumber).sorted().toList();
	                
	                colIdx = 4;
	                for (Integer dn : drawnNumbers) {
	                    Cell cell = rowSorteados.createCell(colIdx++);
	                    cell.setCellValue(dn);
	                    cell.setCellStyle(hitSet.contains(dn) ? hitStyle : borderStyle);
	                }
	                fillNumericCell(rowSorteados, 19, bet.getRealDraw().getOddCount(), borderStyle);
	                fillNumericCell(rowSorteados, 20, bet.getRealDraw().getEvenCount(), borderStyle);
	                fillNumericCell(rowSorteados, 21, bet.getRealDraw().getRepeatedCount(), borderStyle);
	            } else {
	                Cell cellPendente = rowSorteados.createCell(4);
	                cellPendente.setCellValue("Pendente");
	                cellPendente.setCellStyle(borderStyle);
	                for(int i=5; i<=21; i++) rowSorteados.createCell(i).setCellStyle(borderStyle);
	                sheet.addMergedRegion(new CellRangeAddress(rowIdx - 1, rowIdx - 1, 4, 18));
	            }

	            // --- APLICAÇÃO DOS MERGES VERTICAIS ---
	            sheet.addMergedRegion(new CellRangeAddress(apostadosRowIdx, sorteadosRowIdx, 1, 1));
	            sheet.addMergedRegion(new CellRangeAddress(apostadosRowIdx, sorteadosRowIdx, 2, 2));
	            sheet.addMergedRegion(new CellRangeAddress(apostadosRowIdx, sorteadosRowIdx, 22, 22));
	            sheet.addMergedRegion(new CellRangeAddress(apostadosRowIdx, sorteadosRowIdx, 23, 23));

	            // --- Alteração 2: BORDA EXTERNA GROSSA NO BLOCO ---
	            // Definimos a área inteira do bloco (Linha Inicial até Linha Sorteados, Coluna 1 até 23)
	            CellRangeAddress blockRegion = new CellRangeAddress(startRow, sorteadosRowIdx, 1, 23);
	            
	            // Aplicamos a borda média (MEDIUM) nos 4 lados do bloco
	            RegionUtil.setBorderTop(BorderStyle.MEDIUM, blockRegion, sheet);
	            RegionUtil.setBorderBottom(BorderStyle.MEDIUM, blockRegion, sheet);
	            RegionUtil.setBorderLeft(BorderStyle.MEDIUM, blockRegion, sheet);
	            RegionUtil.setBorderRight(BorderStyle.MEDIUM, blockRegion, sheet);

	            rowIdx += 2; // Espaço entre blocos
	        }

	        // --- AJUSTE DE LARGURA ---
	        for (int i = 1; i <= 3; i++) sheet.autoSizeColumn(i);
	        for (int i = 19; i <= 23; i++) sheet.autoSizeColumn(i);
	        
	        for (int i = 4; i <= 18; i++) {
	            sheet.setColumnWidth(i, (int)(4.5 * 256));
	        }

	        workbook.write(out);
	        return out.toByteArray();
	    } catch (IOException e) {
	        throw new RuntimeException("Erro ao exportar", e);
	    }
	}

	// Helper para preenchimento rápido
	private void fillCell(Row row, int col, String val, CellStyle style) {
	    Cell cell = row.createCell(col);
	    cell.setCellValue(val);
	    cell.setCellStyle(style);
	}

	// Métodos Auxiliares para Estilos e Limpeza de Código
	private CellStyle createStyle(Workbook wb, IndexedColors color, boolean bold) {
	    CellStyle style = wb.createCellStyle();
	    if (color != null) {
	        style.setFillForegroundColor(color.getIndex());
	        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
	    }
	    if (bold) {
	        Font font = wb.createFont();
	        font.setBold(true);
	        style.setFont(font);
	    }
	    style.setAlignment(HorizontalAlignment.CENTER);
	    applyBorders(style);
	    return style;
	}

	private void applyBorders(CellStyle style) {
	    style.setBorderTop(BorderStyle.THIN);
	    style.setBorderBottom(BorderStyle.THIN);
	    style.setBorderLeft(BorderStyle.THIN);
	    style.setBorderRight(BorderStyle.THIN);
	}

	private void fillNumericCell(Row row, int col, double val, CellStyle style) {
	    Cell cell = row.createCell(col);
	    cell.setCellValue(val);
	    cell.setCellStyle(style);
	}

	private void autoSizeColumns(Sheet sheet) {
	    for (int i = 1; i <= 3; i++) sheet.autoSizeColumn(i);
	    for (int i = 19; i <= 23; i++) sheet.autoSizeColumn(i);
	}
}