package gabriel.hb.MyLifeBackend.services;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.VerticalAlignment;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.ss.util.RegionUtil;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.client.RestTemplate;

import gabriel.hb.MyLifeBackend.entities.LotofacilBet;
import gabriel.hb.MyLifeBackend.entities.LotofacilBetNumber;
import gabriel.hb.MyLifeBackend.entities.LotofacilDraw;
import gabriel.hb.MyLifeBackend.entities.LotofacilDrawNumber;
import gabriel.hb.MyLifeBackend.repositories.LotofacilBetRepository;
import gabriel.hb.MyLifeBackend.repositories.LotofacilDrawRepository;
import gabriel.hb.MyLifeBackend.repositories.projection.BetSummaryProjection;
import gabriel.hb.MyLifeBackend.repositories.projection.ParityGroupProjection;
import gabriel.hb.MyLifeBackend.repositories.projection.RepetitionGroupProjection;
import gabriel.hb.MyLifeBackend.resources.dto.BetGraphicsResponse;
import gabriel.hb.MyLifeBackend.resources.dto.BetSummaryResponse;
import gabriel.hb.MyLifeBackend.resources.dto.PlaceBetRequest;
import gabriel.hb.MyLifeBackend.services.dto.CaixaDraw;
import gabriel.hb.MyLifeBackend.services.exceptions.DatabaseException;
import gabriel.hb.MyLifeBackend.services.exceptions.ResourceNotFoundException;

@Service /* Registra a classe como um componente/service do spring e vai poder ser injetado no LotofacilBetResource */
public class LotofacilBetService {
	
	/* O Spring resolve essa injeção de dependencia e associar uma instancia de LotofacilBetRepository */
	@Autowired private LotofacilBetRepository repository;
	@Autowired private LotofacilDrawRepository drawRepository;
	
	private final String CAIXA_API_URL = "https://servicebus2.caixa.gov.br/portaldeloterias/api/lotofacil/";
	
    /* Listar de todos os concursos */
	public List<LotofacilBet> findAll(){
		return repository.findAll();
	}
	
    /* Consultar concurso por Id */
	public LotofacilBet findById(Long id) {
        Optional<LotofacilBet> obj = repository.findById(id); // o findById retona um Optional
        return obj.orElseThrow(() -> new ResourceNotFoundException(id));
	}
	
	public List<LotofacilBet> findByTargetDrawId(Long targetDrawId) {
		List<LotofacilBet> list = repository.findByTargetDrawId(targetDrawId);
	    if (list.isEmpty()) throw new ResourceNotFoundException(targetDrawId);
	    return list;
	}
	
	/* Inserir nova aposta - Refatorado para usar a avaliação unificada */
	@Transactional
	public LotofacilBet insert(PlaceBetRequest dto) {
		LotofacilBet bet = new LotofacilBet();
        bet.setBetDate(dto.getBetDate());
        bet.setTargetDrawId(dto.getTargetDrawId());
        bet.setCost(3.50);
        bet.setAutoGenerated(dto.isAutoGenerated());
        bet.setChecked(false);
        bet.setHits(0);

        for (Integer num : dto.getBetNumbers()) {
            LotofacilBetNumber betNumber = new LotofacilBetNumber();
            betNumber.setNumber(num);
            betNumber.setBet(bet); 
            bet.getBetNumbers().add(betNumber);
        }

        // Obtém dezenas do concurso anterior (se existir)
        List<Integer> previousNumbers = getPreviousDrawNumbers(dto.getTargetDrawId());
        
        // Tenta obter o concurso alvo (se já existir no banco)
        Optional<LotofacilDraw> targetDrawOpt = drawRepository.findById(dto.getTargetDrawId());
        LotofacilDraw targetDraw = targetDrawOpt.orElse(null);
        List<Integer> targetNums = null;
        List<CaixaDraw.RateioPremio> premios = null;

        if (targetDraw != null) {
            targetNums = targetDraw.getDrawNumbers().stream()
                    .map(LotofacilDrawNumber::getNumber).collect(Collectors.toList());
            
            // Se for oficial, busca os prêmios na hora para aposta antiga
            if (targetDraw.isOfficial()) {
                try {
                    RestTemplate rt = new RestTemplate();
                    CaixaDraw apiDraw = rt.getForObject(CAIXA_API_URL + dto.getTargetDrawId(), CaixaDraw.class);
                    if (apiDraw != null) premios = apiDraw.getListaRateioPremio();
                } catch(Exception ignored) {}
            }
        }

        // Passa por avaliação de acertos, paridade e repetições
        evaluateBet(bet, targetNums, previousNumbers, targetDraw, premios);

		return repository.save(bet);
	}
	
	/* Método ÚNICO que resolve as apostas do concurso salvo e as repetições do concurso seguinte */
	@Transactional
	public void processBetsForDraw(LotofacilDraw savedDraw, CaixaDraw caixaDraw) {
	    List<CaixaDraw.RateioPremio> premios = (caixaDraw != null) ? caixaDraw.getListaRateioPremio() : null;

	    // 1. Processar apostas do concurso atual (Acertos, Paridade, Prêmios e Repetição baseada no concurso N-1)
	    List<LotofacilBet> currentBets = repository.findByTargetDrawId(savedDraw.getId());
	    if (!currentBets.isEmpty()) {
	        List<Integer> currentDrawNumbers = savedDraw.getDrawNumbers().stream()
	                .map(LotofacilDrawNumber::getNumber).collect(Collectors.toList());
	        
	        List<Integer> previousNumbers = getPreviousDrawNumbers(savedDraw.getId());

	        for (LotofacilBet bet : currentBets) {
	            evaluateBet(bet, currentDrawNumbers, previousNumbers, savedDraw, premios);
	        }
	        repository.saveAll(currentBets);
	    }

	    // 2. Processar apostas do PRÓXIMO concurso (apenas atualizar a Repetição baseada no concurso recém salvo)
	    List<LotofacilBet> futureBets = repository.findByTargetDrawId(savedDraw.getId() + 1);
	    if (!futureBets.isEmpty()) {
	        List<Integer> officialNumbersForFuture = savedDraw.getDrawNumbers().stream()
	                .map(LotofacilDrawNumber::getNumber).collect(Collectors.toList());
	        
	        for (LotofacilBet bet : futureBets) {
	            evaluateBet(bet, null, officialNumbersForFuture, null, null);
	        }
	        repository.saveAll(futureBets);
	    }
	}

    // Retorna a lista de dezenas do concurso anterior
	private List<Integer> getPreviousDrawNumbers(Long currentDrawId) {
	    List<Integer> previousNumbers = new ArrayList<>();
	    Optional<LotofacilDraw> previousDrawOpt = drawRepository.findById(currentDrawId - 1);
	    if (previousDrawOpt.isPresent()) {
	        previousNumbers = previousDrawOpt.get().getDrawNumbers().stream()
	                .map(LotofacilDrawNumber::getNumber).collect(Collectors.toList());
	    }
	    return previousNumbers;
	}

	/* Motor de Regras: Centraliza os cálculos dinamicamente se as informações existirem */
	private void evaluateBet(LotofacilBet bet, List<Integer> targetDrawNumbers, List<Integer> previousNumbers, LotofacilDraw targetDraw, List<CaixaDraw.RateioPremio> premios) {
	    int hits = 0;
	    int repeatedCount = 0;
	    int evenCount = 0;
	    int oddCount = 0;

	    for (LotofacilBetNumber betNumber : bet.getBetNumbers()) {
	        int num = betNumber.getNumber();
	        
	        // Paridade
	        if (num % 2 == 0) evenCount++;
	        else oddCount++;
	        
	        // Repetições (só avalia se a lista do anterior for preenchida)
	        if (previousNumbers != null && !previousNumbers.isEmpty()) {
	            boolean isRep = previousNumbers.contains(num);
	            betNumber.setIsRepeated(isRep);
	            if (isRep) repeatedCount++;
	        }
	        
	        // Acertos (só avalia se o concurso alvo já tiver ocorrido)
	        if (targetDrawNumbers != null) {
	            if (targetDrawNumbers.contains(num)) {
	                betNumber.setWasCorrectly(true);
	                hits++;
	            } else {
	                betNumber.setWasCorrectly(false);
	            }
	        }
	    }

	    bet.setEvenCount(evenCount);
	    bet.setOddCount(oddCount);
	    if (previousNumbers != null && !previousNumbers.isEmpty()) {
	        bet.setRepeatedCount(repeatedCount);
	    }

	    // Consolida resultados finais de conferência e prêmios
	    if (targetDraw != null) {
	        bet.setHits(hits);
	        bet.setChecked(true);
	        bet.setRealDraw(targetDraw);

	        double prizeValue = 0.0;
	        if (hits >= 11 && premios != null && targetDraw.isOfficial()) {
	            String targetDesc = hits + " acertos";
	            for (CaixaDraw.RateioPremio r : premios) {
	                if (r.getDescricaoFaixa().toLowerCase().contains(targetDesc)) {
	                    prizeValue = r.getValorPremio();
	                    break;
	                }
	            }
	        }
	        bet.setPrize(prizeValue);
	    }
	}
	
	public void delete(Long id) {
	    try {
	        if (repository.existsById(id)) repository.deleteById(id);			
	        else throw new ResourceNotFoundException(id);		
	    } catch (DataIntegrityViolationException e) {			
	        throw new DatabaseException(e.getMessage());		
	    }	
	}
	
	public BetSummaryResponse getSummary() {
	    BetSummaryProjection projection = repository.getBetSummaryData();
	    
	    // O Saldo deve considerar o custo de TODAS, mas o prêmio de TODAS (que é 0 para as não conferidas)
	    Double balance = projection.getTotalReturn() - projection.getTotalInvested();
	    
	    Double averageHits = repository.getAverageHits(); // Agora filtrado por isChecked = true
	    Long totalWinningBets = repository.countWinningBetsChecked(); // Agora filtrado
	    Long totalChecked = repository.countAllCheckedBets();
	    
	    // Cálculo de taxa de vitória (Ex: 0.15 para 15%)
	    Double winRate = (totalChecked > 0) ? (totalWinningBets.doubleValue() / totalChecked) : 0.0;

	    return new BetSummaryResponse(
	        projection.getTotalBets(),
	        projection.getTotalInvested(),
	        projection.getTotalReturn(),
	        balance,
	        averageHits,
	        repository.countByAutoGeneratedTrue(),
	        repository.countByAutoGeneratedFalse(),
	        totalWinningBets,
	        winRate // Adicione este campo ao seu DTO no Java e no Angular
	    );
	}

	// Novo método para retornar os dados dos gráficos
	public BetGraphicsResponse getGraphicsData() {
	    List<ParityGroupProjection> parities = repository.getBetsGroupedByParity();
	    List<RepetitionGroupProjection> repetitions = repository.getBetsGroupedByRepetition();
	    Long parityHits = repository.countExactParityHits();
	    Long repetitionHits = repository.countExactRepetitionHits();

	    return new BetGraphicsResponse(parities, repetitions, parityHits, repetitionHits);
	}

	public Page<LotofacilBet> findAllPaginated(Pageable pageable) {
	    return repository.findAll(pageable);
	}
	
	public byte[] exportBetsToExcel() {
	    List<LotofacilBet> bets = repository.findAll();
	    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");

	    try (Workbook workbook = new XSSFWorkbook(); ByteArrayOutputStream out = new ByteArrayOutputStream()) {
	        
	        // ==========================================
	        // ESTILOS COMUNS
	        // ==========================================
	        CellStyle headerStyle = createStyle(workbook, IndexedColors.GREY_25_PERCENT, true);
	        CellStyle borderStyle = createStyle(workbook, null, false);
	        CellStyle repeatedStyle = createStyle(workbook, IndexedColors.LEMON_CHIFFON, false);
	        CellStyle hitStyle = createStyle(workbook, IndexedColors.LIGHT_GREEN, false);
	        
	        CellStyle mergedStyle = createStyle(workbook, null, false);
	        mergedStyle.setVerticalAlignment(VerticalAlignment.CENTER);

	        CellStyle boldLabelStyle = workbook.createCellStyle();
	        Font boldFont = workbook.createFont();
	        boldFont.setBold(true);
	        boldLabelStyle.setFont(boldFont);

	        // ==========================================
	        // ABA 1: RELATÓRIO DE APOSTAS
	        // ==========================================
	        Sheet sheetApostas = workbook.createSheet("Relatório de Apostas");
	        int rowIdx = 2;

	        for (LotofacilBet bet : bets) {
	            int startRow = rowIdx; 
	            int apostadosRowIdx = rowIdx + 1;
	            int sorteadosRowIdx = rowIdx + 2;

	            // CABEÇALHO DO BLOCO
	            Row headerRow = sheetApostas.createRow(rowIdx++);
	            String[] cols = {"", "Data Aposta", "Concurso", "", "Dezenas", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Qtd Impar", "Qtd Par", "Qtd Rep", "Qtd Acert", "Prêmio"};
	            
	            for (int i = 1; i < cols.length; i++) {
	                Cell cell = headerRow.createCell(i);
	                cell.setCellValue(cols[i]);
	                cell.setCellStyle(headerStyle); 
	            }
	            sheetApostas.addMergedRegion(new CellRangeAddress(startRow, startRow, 4, 18));

	            // LINHA: APOSTADOS
	            Row rowApostados = sheetApostas.createRow(rowIdx++);
	            List<LotofacilBetNumber> betNumbers = new ArrayList<>(bet.getBetNumbers());
	            betNumbers.sort(Comparator.comparingInt(LotofacilBetNumber::getNumber));

	            fillCell(rowApostados, 1, bet.getBetDate() != null ? bet.getBetDate().format(dtf) : "", mergedStyle);
	            fillCell(rowApostados, 2, bet.getTargetDrawId().toString(), mergedStyle);
	            fillCell(rowApostados, 22, String.valueOf(bet.getHits()), mergedStyle);
	            fillCell(rowApostados, 23, bet.getPrize() != null ? String.format("%.2f", bet.getPrize()) : "0.00", mergedStyle);

	            fillCell(rowApostados, 3, "Apostados", createStyle(workbook, null, true));

	            int colIdx = 4;
	            for (LotofacilBetNumber bn : betNumbers) {
	                Cell cell = rowApostados.createCell(colIdx++);
	                cell.setCellValue(bn.getNumber());
	                cell.setCellStyle(bn.getIsRepeated() ? repeatedStyle : borderStyle);
	            }
	            
	            fillNumericCell(rowApostados, 19, bet.getOddCount(), borderStyle);
	            fillNumericCell(rowApostados, 20, bet.getEvenCount(), borderStyle);
	            fillNumericCell(rowApostados, 21, bet.getRepeatedCount(), borderStyle);

	            // LINHA: SORTEADOS
	            Row rowSorteados = sheetApostas.createRow(rowIdx++);
	            rowSorteados.createCell(1).setCellStyle(mergedStyle);
	            rowSorteados.createCell(2).setCellStyle(mergedStyle);
	            rowSorteados.createCell(22).setCellStyle(mergedStyle);
	            rowSorteados.createCell(23).setCellStyle(mergedStyle);

	            fillCell(rowSorteados, 3, "Sorteados", createStyle(workbook, null, true));

	            if (bet.isChecked() && bet.getRealDraw() != null) {
	                Set<Integer> hitSet = betNumbers.stream().filter(LotofacilBetNumber::isWasCorrectly).map(LotofacilBetNumber::getNumber).collect(Collectors.toSet());
	                List<Integer> drawnNumbers = bet.getRealDraw().getDrawNumbers().stream().map(LotofacilDrawNumber::getNumber).sorted().toList();
	                
	                colIdx = 4;
	                for (Integer dn : drawnNumbers) {
	                    Cell cell = rowSorteados.createCell(colIdx++);
	                    cell.setCellValue(dn);
	                    cell.setCellStyle(hitSet.contains(dn) ? hitStyle : borderStyle);
	                }
	                fillNumericCell(rowSorteados, 19, bet.getRealDraw().getOddCount(), borderStyle);
	                fillNumericCell(rowSorteados, 20, bet.getRealDraw().getEvenCount(), borderStyle);
	                fillNumericCell(rowSorteados, 21, bet.getRealDraw().getRepeatedCount(), borderStyle);
	            } else {
	                Cell cellPendente = rowSorteados.createCell(4);
	                cellPendente.setCellValue("Pendente");
	                cellPendente.setCellStyle(borderStyle);
	                for(int i=5; i<=21; i++) rowSorteados.createCell(i).setCellStyle(borderStyle);
	                sheetApostas.addMergedRegion(new CellRangeAddress(rowIdx - 1, rowIdx - 1, 4, 18));
	            }

	            // MERGES VERTICAIS E BORDAS
	            sheetApostas.addMergedRegion(new CellRangeAddress(apostadosRowIdx, sorteadosRowIdx, 1, 1));
	            sheetApostas.addMergedRegion(new CellRangeAddress(apostadosRowIdx, sorteadosRowIdx, 2, 2));
	            sheetApostas.addMergedRegion(new CellRangeAddress(apostadosRowIdx, sorteadosRowIdx, 22, 22));
	            sheetApostas.addMergedRegion(new CellRangeAddress(apostadosRowIdx, sorteadosRowIdx, 23, 23));

	            CellRangeAddress blockRegion = new CellRangeAddress(startRow, sorteadosRowIdx, 1, 23);
	            RegionUtil.setBorderTop(BorderStyle.MEDIUM, blockRegion, sheetApostas);
	            RegionUtil.setBorderBottom(BorderStyle.MEDIUM, blockRegion, sheetApostas);
	            RegionUtil.setBorderLeft(BorderStyle.MEDIUM, blockRegion, sheetApostas);
	            RegionUtil.setBorderRight(BorderStyle.MEDIUM, blockRegion, sheetApostas);

	            rowIdx += 2; 
	        }

	        for (int i = 1; i <= 3; i++) sheetApostas.autoSizeColumn(i);
	        for (int i = 19; i <= 23; i++) sheetApostas.autoSizeColumn(i);
	        for (int i = 4; i <= 18; i++) sheetApostas.setColumnWidth(i, (int)(3.5 * 256));

	     // ==========================================
	        // ABA 2: RESUMO GERAL (DASHBOARD)
	        // ==========================================
	        Sheet sheetResumo = workbook.createSheet("Resumo Geral");
	        
	        // --- 1. Calcular os dados na memória ---
	        double totalInvested = 0.0;
	        double totalReturn = 0.0;
	        long winningBets = 0;
	        long checkedBets = 0;
	        long totalHits = 0;
	        long autoGenCount = 0;
	        long manualCount = 0;
	        
	        Map<String, Integer> paritiesDist = new HashMap<>();
	        Map<Integer, Integer> repDist = new HashMap<>();

	        for (LotofacilBet bet : bets) {
	            totalInvested += bet.getCost();
	            if (bet.getPrize() != null && bet.getPrize() > 0) {
	                totalReturn += bet.getPrize();
	                winningBets++;
	            }
	            if (bet.isChecked()) {
	                checkedBets++;
	                totalHits += bet.getHits();
	            }
	            if (bet.getAutoGenerated()) autoGenCount++; else manualCount++;

	            String parityKey = bet.getOddCount() + "Í / " + bet.getEvenCount() + "P";
	            paritiesDist.put(parityKey, paritiesDist.getOrDefault(parityKey, 0) + 1);
	            repDist.put(bet.getRepeatedCount(), repDist.getOrDefault(bet.getRepeatedCount(), 0) + 1);
	        }

	        double balance = totalReturn - totalInvested;
	        double avgHits = checkedBets > 0 ? (double) totalHits / checkedBets : 0.0;
	        double winRate = checkedBets > 0 ? ((double) winningBets / checkedBets) * 100 : 0.0;

	        // --- Novos Estilos para o Dashboard ---
	        CellStyle boldLabelStyle2 = createStyle(workbook, null, true); // Com bordas
	        CellStyle styleRed = createStyle(workbook, IndexedColors.ROSE, true); // Vermelho/Rosa para saída
	        CellStyle styleGreen = createStyle(workbook, IndexedColors.LIGHT_GREEN, true); // Verde para entrada

	        // --- 2. Imprimir Lado a Lado (Geral e Financeiro) ---
	        int rIdx = 1;
	        
	        // Cabeçalhos das duas tabelas
	        createDashboardHeader(sheetResumo, rIdx, "ESTATÍSTICAS GERAIS", headerStyle);
	        createDashboardHeaderRight(sheetResumo, rIdx, "BALANÇO FINANCEIRO", headerStyle);
	        rIdx++;

	        // Linha 2
	        createDashboardRow(sheetResumo, rIdx, "Total de Apostas:", String.valueOf(bets.size()), borderStyle, boldLabelStyle2);
	        createDashboardRowRight(sheetResumo, rIdx, "Total Investido (R$):", String.format("%.2f", totalInvested), styleRed, boldLabelStyle2);
	        rIdx++;

	        // Linha 3
	        createDashboardRow(sheetResumo, rIdx, "Apostas Conferidas:", String.valueOf(checkedBets), borderStyle, boldLabelStyle2);
	        createDashboardRowRight(sheetResumo, rIdx, "Retorno Total (R$):", String.format("%.2f", totalReturn), styleGreen, boldLabelStyle2);
	        rIdx++;

	        // Linha 4
	        createDashboardRow(sheetResumo, rIdx, "Média de Acertos:", String.format("%.2f", avgHits), borderStyle, boldLabelStyle2);
	        CellStyle balanceStyle = balance >= 0 ? styleGreen : styleRed;
	        createDashboardRowRight(sheetResumo, rIdx, "Saldo Final (R$):", String.format("%.2f", balance), balanceStyle, boldLabelStyle2);
	        rIdx++;

	        // Linha 5 em diante (Apenas Estatísticas na Esquerda)
	        createDashboardRow(sheetResumo, rIdx++, "Apostas Premiadas:", String.valueOf(winningBets), borderStyle, boldLabelStyle2);
	        createDashboardRow(sheetResumo, rIdx++, "Taxa de Sucesso:", String.format("%.1f%%", winRate), borderStyle, boldLabelStyle2);
	        createDashboardRow(sheetResumo, rIdx++, "Origem - Algoritmo:", String.valueOf(autoGenCount), borderStyle, boldLabelStyle2);
	        createDashboardRow(sheetResumo, rIdx++, "Origem - Manual:", String.valueOf(manualCount), borderStyle, boldLabelStyle2);

	        rIdx += 2; // Espaço antes das distribuições

	        // --- 3. Imprimir Tabelas de Distribuição para Gráficos ---
	        int tableStartRow = rIdx;

	        // Tabela de Paridade (Esquerda)
	        createDashboardHeader(sheetResumo, rIdx++, "DISTRIBUIÇÃO DE PARIDADE", headerStyle);
	        Row subH1 = sheetResumo.createRow(rIdx++);
	        fillCell(subH1, 1, "Padrão", headerStyle);
	        fillCell(subH1, 2, "Qtd de Apostas", headerStyle);
	        
	        for (Map.Entry<String, Integer> entry : paritiesDist.entrySet()) {
	            Row row = sheetResumo.createRow(rIdx++);
	            fillCell(row, 1, entry.getKey(), borderStyle);
	            fillNumericCell(row, 2, entry.getValue(), borderStyle);
	        }

	        // Tabela de Repetição (Direita)
	        int rightIdx = tableStartRow;
	        createDashboardHeaderRight(sheetResumo, rightIdx++, "DISTRIBUIÇÃO DE REPETIÇÕES", headerStyle);
	        Row subH2 = sheetResumo.getRow(rightIdx);
	        if (subH2 == null) subH2 = sheetResumo.createRow(rightIdx);
	        rightIdx++;
	        fillCell(subH2, 4, "Repetidas", headerStyle);
	        fillCell(subH2, 5, "Qtd de Apostas", headerStyle);

	        for (Map.Entry<Integer, Integer> entry : repDist.entrySet()) {
	            Row row = sheetResumo.getRow(rightIdx);
	            if (row == null) row = sheetResumo.createRow(rightIdx);
	            rightIdx++;
	            fillNumericCell(row, 4, entry.getKey(), borderStyle);
	            fillNumericCell(row, 5, entry.getValue(), borderStyle);
	        }

	        // --- 4. Definir Larguras Fixas (Resolve o problema da tabela estreita) ---
	        sheetResumo.setColumnWidth(1, 22 * 256); // Coluna dos Rótulos Esquerdos
	        sheetResumo.setColumnWidth(2, 16 * 256); // Coluna dos Valores Esquerdos
	        sheetResumo.setColumnWidth(4, 24 * 256); // Coluna dos Rótulos Direitos
	        sheetResumo.setColumnWidth(5, 16 * 256); // Coluna dos Valores Direitos

	        workbook.write(out);
	        return out.toByteArray();
	    } catch (IOException e) {
	        throw new RuntimeException("Erro ao exportar", e);
	    }
	}

	// ==========================================
	// NOVOS MÉTODOS AUXILIARES
	// ==========================================

	private void createDashboardHeader(Sheet sheet, int rowIdx, String title, CellStyle style) {
	    Row row = sheet.createRow(rowIdx);
	    fillCell(row, 1, title, style);
	    fillCell(row, 2, "", style);
	    sheet.addMergedRegion(new CellRangeAddress(rowIdx, rowIdx, 1, 2));
	}

	private void createDashboardHeaderRight(Sheet sheet, int rowIdx, String title, CellStyle style) {
	    Row row = sheet.getRow(rowIdx);
	    if(row == null) row = sheet.createRow(rowIdx);
	    fillCell(row, 4, title, style);
	    fillCell(row, 5, "", style);
	    sheet.addMergedRegion(new CellRangeAddress(rowIdx, rowIdx, 4, 5));
	}

	private void createDashboardRow(Sheet sheet, int rowIdx, String label, String value, CellStyle valStyle, CellStyle labelStyle) {
	    Row row = sheet.createRow(rowIdx);
	    fillCell(row, 1, label, labelStyle);
	    fillCell(row, 2, value, valStyle);
	}

	private void createDashboardRowRight(Sheet sheet, int rowIdx, String label, String value, CellStyle valStyle, CellStyle labelStyle) {
	    Row row = sheet.getRow(rowIdx);
	    if (row == null) row = sheet.createRow(rowIdx);
	    fillCell(row, 4, label, labelStyle);
	    fillCell(row, 5, value, valStyle);
	}

	private void fillCell(Row row, int col, String val, CellStyle style) {
	    Cell cell = row.createCell(col);
	    cell.setCellValue(val);
	    cell.setCellStyle(style);
	}

	private CellStyle createStyle(Workbook wb, IndexedColors color, boolean bold) {
	    CellStyle style = wb.createCellStyle();
	    if (color != null) {
	        style.setFillForegroundColor(color.getIndex());
	        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
	    }
	    if (bold) {
	        Font font = wb.createFont();
	        font.setBold(true);
	        style.setFont(font);
	    }
	    style.setAlignment(HorizontalAlignment.CENTER);
	    style.setBorderTop(BorderStyle.THIN);
	    style.setBorderBottom(BorderStyle.THIN);
	    style.setBorderLeft(BorderStyle.THIN);
	    style.setBorderRight(BorderStyle.THIN);
	    return style;
	}

	private void fillNumericCell(Row row, int col, double val, CellStyle style) {
	    Cell cell = row.createCell(col);
	    cell.setCellValue(val);
	    cell.setCellStyle(style);
	}
}