package gabriel.hb.MyLifeBackend.resources.dto;

public class BetSummaryResponse {
	
    private Long totalBets;
    private Double totalInvested;
    private Double totalReturn;
    private Double balance;
    private Double averageHits;
    private Long totalAutoGenerated;
    private Long totalManual;
    private Long totalWinningBets;
    private Double winRate;

    public BetSummaryResponse(Long totalBets, Double totalInvested, Double totalReturn, Double balance, 
            Double averageHits, Long totalAutoGenerated, Long totalManual, Long totalWinningBets, Double winRate) {
		this.totalBets = totalBets;
		this.totalInvested = totalInvested;
		this.totalReturn = totalReturn;
		this.balance = balance;
		this.averageHits = averageHits;
		this.totalAutoGenerated = totalAutoGenerated;
		this.totalManual = totalManual;
		this.totalWinningBets = totalWinningBets;
		this.setWinRate(winRate);
	}
	
	// Getters e Setters
	public Long getTotalBets() { return totalBets; }
	public void setTotalBets(Long totalBets) { this.totalBets = totalBets; }
	public Double getTotalInvested() { return totalInvested; }
	public void setTotalInvested(Double totalInvested) { this.totalInvested = totalInvested; }
	public Double getTotalReturn() { return totalReturn; }
	public void setTotalReturn(Double totalReturn) { this.totalReturn = totalReturn; }
	public Double getBalance() { return balance; }
	public void setBalance(Double balance) { this.balance = balance; }
	public Double getAverageHits() { return averageHits; }
	public void setAverageHits(Double averageHits) { this.averageHits = averageHits; }
	public Long getTotalAutoGenerated() { return totalAutoGenerated; }
	public void setTotalAutoGenerated(Long totalAutoGenerated) { this.totalAutoGenerated = totalAutoGenerated; }
	public Long getTotalManual() { return totalManual; }
	public void setTotalManual(Long totalManual) { this.totalManual = totalManual; }
	public Long getTotalWinningBets() { return totalWinningBets; }
	public void setTotalWinningBets(Long totalWinningBets) { this.totalWinningBets = totalWinningBets; }

	public Double getWinRate() {
		return winRate;
	}

	public void setWinRate(Double winRate) {
		this.winRate = winRate;
	}
}
