package gabriel.hb.MyLifeBackend.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import gabriel.hb.MyLifeBackend.entities.LotofacilBet;
import gabriel.hb.MyLifeBackend.repositories.projection.BetSummaryProjection;
import gabriel.hb.MyLifeBackend.repositories.projection.ParityGroupProjection;
import gabriel.hb.MyLifeBackend.repositories.projection.RepetitionGroupProjection;

@Repository
public interface LotofacilBetRepository extends JpaRepository<LotofacilBet, Long>{
	
    Optional<LotofacilBet> findTopByOrderByIdDesc();
    
    List<LotofacilBet> findByTargetDrawId(Long targetDrawId);
    
    List<LotofacilBet> findByTargetDrawIdAndIsCheckedFalse(Long targetDrawId);
    
    @Query("SELECT COUNT(b) as totalBets, COALESCE(SUM(b.cost), 0.0) as totalInvested, COALESCE(SUM(b.prize), 0.0) as totalReturn FROM LotofacilBet b")
    BetSummaryProjection getBetSummaryData();

    // ---- NOVAS QUERIES PARA O DASHBOARD ----
    
    // Média geral de acertos
 // No arquivo LotofacilBetRepository.java

	 // 1. Média de acertos apenas de jogos já conferidos
	 @Query("SELECT COALESCE(AVG(b.hits), 0.0) FROM LotofacilBet b WHERE b.isChecked = true")
	 Double getAverageHits();
	
	 // 2. Contagem de apostas premiadas apenas entre as conferidas
	 @Query("SELECT COUNT(b) FROM LotofacilBet b WHERE b.isChecked = true AND b.prize > 0")
	 long countWinningBetsChecked();
	
	 // 3. Opcional: Contagem de apostas conferidas totais (para cálculo de taxa de vitória)
	 @Query("SELECT COUNT(b) FROM LotofacilBet b WHERE b.isChecked = true")
	 long countAllCheckedBets();

    // Contagens específicas
    long countByAutoGeneratedTrue();
    long countByAutoGeneratedFalse();
    long countByPrizeGreaterThan(Double value);

    // Agrupamento para Gráfico de Pizza: Paridade
    @Query("SELECT b.oddCount as oddCount, b.evenCount as evenCount, COUNT(b) as total FROM LotofacilBet b GROUP BY b.oddCount, b.evenCount")
    List<ParityGroupProjection> getBetsGroupedByParity();

    // Agrupamento para Gráfico de Pizza: Repetição
    @Query("SELECT b.repeatedCount as repeatedCount, COUNT(b) as total FROM LotofacilBet b GROUP BY b.repeatedCount")
    List<RepetitionGroupProjection> getBetsGroupedByRepetition();

    // Acertos em cheio na estratégia de Paridade (A aposta tinha X ímpares, e o sorteio real também teve X ímpares)
    @Query("SELECT COUNT(b) FROM LotofacilBet b WHERE b.isChecked = true AND b.oddCount = b.realDraw.oddCount")
    long countExactParityHits();

    // Acertos em cheio na estratégia de Repetição (A aposta repetiu X, e o sorteio real também repetiu X)
    @Query("SELECT COUNT(b) FROM LotofacilBet b WHERE b.isChecked = true AND b.repeatedCount = b.realDraw.repeatedCount")
    long countExactRepetitionHits();
}